-- EBiTO Coin production foundation. Run in Supabase SQL Editor.

alter table public.users add column if not exists airdrop_points bigint not null default 0;
alter table public.users add column if not exists tap_power integer not null default 1;
alter table public.users add column if not exists profit_hour bigint not null default 0;
alter table public.users add column if not exists last_tap_at timestamptz;
alter table public.users add column if not exists last_daily_combo date;
alter table public.users add column if not exists daily_combo_claimed boolean not null default false;
alter table public.upgrades add column if not exists category text not null default 'General';
alter table public.upgrades add column if not exists icon text default '🃏';

create table if not exists public.game_scores(
 id bigint generated by default as identity primary key,
 telegram_id bigint not null,
 score integer not null,
 reward bigint not null default 0,
 created_at timestamptz not null default now()
);
create table if not exists public.daily_combos(
 combo_date date primary key,
 card_1 bigint not null references public.upgrades(id) on delete cascade,
 card_2 bigint not null references public.upgrades(id) on delete cascade,
 card_3 bigint not null references public.upgrades(id) on delete cascade,
 reward bigint not null default 5000000
);
create table if not exists public.transactions(
 id bigint generated by default as identity primary key,
 telegram_id bigint not null,
 type text not null,
 amount bigint not null,
 reference_id text,
 metadata jsonb,
 created_at timestamptz not null default now()
);
create table if not exists public.admin_actions(
 id bigint generated by default as identity primary key,
 admin_telegram_id bigint not null,
 action text not null,
 target_telegram_id bigint,
 metadata jsonb,
 created_at timestamptz not null default now()
);

create index if not exists game_scores_user_idx on public.game_scores(telegram_id, created_at desc);
create index if not exists transactions_user_idx on public.transactions(telegram_id, created_at desc);
create index if not exists admin_actions_target_idx on public.admin_actions(target_telegram_id, created_at desc);

alter table public.users enable row level security;
alter table public.tasks enable row level security;
alter table public.user_tasks enable row level security;
alter table public.referrals enable row level security;
alter table public.upgrades enable row level security;
alter table public.user_upgrades enable row level security;
alter table public.game_scores enable row level security;
alter table public.daily_combos enable row level security;
alter table public.transactions enable row level security;
alter table public.admin_actions enable row level security;

-- Browser only needs to READ public cards/tasks/leaderboard data.
drop policy if exists upgrades_public_read on public.upgrades;
create policy upgrades_public_read on public.upgrades for select to anon, authenticated using (true);
drop policy if exists tasks_public_read on public.tasks;
create policy tasks_public_read on public.tasks for select to anon, authenticated using (active = true);
drop policy if exists users_public_leaderboard on public.users;
create policy users_public_leaderboard on public.users for select to anon, authenticated using (true);

-- No browser INSERT/UPDATE/DELETE policies are created for economy tables.
-- All coin, energy, task, upgrade, combo and admin mutations must go through Edge Functions.

insert into public.upgrades(name,description,level,cost,tap_bonus,energy_bonus,category,icon)
select * from (values
('EBiTO HQ','Build the core EBiTO operation.',1,100,1,20,'Team','🏢'),
('Creator Studio','Increase content and community output.',1,500,3,30,'Marketing','🎬'),
('Community Engine','Grow your active miner network.',1,2500,8,50,'Community','👥'),
('Web3 Lab','Unlock advanced ecosystem power.',1,10000,20,100,'Web3','🌐'),
('Nigeria License','Regional expansion card.',1,25000,45,150,'Country Licenses','🇳🇬'),
('Ghana License','West African expansion card.',1,50000,80,200,'Country Licenses','🇬🇭'),
('UK License','International expansion card.',1,150000,180,300,'Country Licenses','🇬🇧'),
('US License','Major market expansion card.',1,500000,500,500,'Country Licenses','🇺🇸'),
('AI Mining','Automate part of the mining operation.',1,1000000,1200,800,'Technology','🤖')
) v(name,description,level,cost,tap_bonus,energy_bonus,category,icon)
where not exists(select 1 from public.upgrades u where u.name=v.name);

insert into public.tasks(title,description,reward,task_type,url,active)
select * from (values
('Join EBiTO Community','Open the official EBiTO community channel.',1000,'social','https://t.me/Ebitocoinbot',true),
('Share EBiTO','Share EBiTO with friends and grow the network.',2500,'social','https://t.me/Ebitocoinbot',true),
('Follow EBiTO Updates','Follow the project updates and announcements.',1500,'social','https://t.me/Ebitocoinbot',true)
) v(title,description,reward,task_type,url,active)
where not exists(select 1 from public.tasks t where t.title=v.title);
